import { useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronRight, CreditCard, FileText, Home, Landmark, Menu, MessageSquare, MoreVertical, PanelLeft, PiggyBank, QrCode, ReceiptText, Search, Send, ShieldCheck, Sparkles, WalletCards, X } from "lucide-react";

type View = "home" | "products" | "actions" | "applications" | "menu" | "transactions";
type Panel = "transfer" | "qr" | "bill" | null;

const shortcuts = [
  { label: "Varlıklarım", icon: PiggyBank, tone: "bg-[#fde6e9] text-[#d3132b]" },
  { label: "Son İşlemler", icon: FileText, tone: "bg-[#eeeafb] text-[#7466b6]" },
  { label: "QR ile Para\nÇekme", icon: QrCode, tone: "bg-[#fff0e8] text-[#e07c4f]" },
  { label: "Para\nTransferi", icon: Send, tone: "bg-[#e7f0f9] text-[#40739f]" },
];
const navItems = [
  { label: "Ana Sayfa", view: "home" as View, icon: Home }, { label: "Ürünler", view: "products" as View, icon: WalletCards },
  { label: "İşlemler", view: "actions" as View, icon: ArrowRight }, { label: "Başvurular", view: "applications" as View, icon: Check }, { label: "Tüm Menü", view: "menu" as View, icon: Menu },
];

export function ZiratMobile() {
  const [view, setView] = useState<View>("home");
  const [panel, setPanel] = useState<Panel>(null);
  const [visible, setVisible] = useState(true);
  const [tab, setTab] = useState<"accounts" | "cards">("accounts");
  const [confirmed, setConfirmed] = useState(false);
  const [recipient, setRecipient] = useState("Ayşe Demir");
  const [amount, setAmount] = useState("850,00");
  const close = () => { setPanel(null); setConfirmed(false); };
  return <main className="min-h-[100dvh] bg-[#f4f1f2] text-[#242326] antialiased"><div className="mx-auto min-h-[100dvh] w-full max-w-[430px] overflow-hidden bg-[#fbfafa] shadow-[0_0_55px_rgba(93,23,30,.12)]">
    {view === "home" && <><header className="relative overflow-hidden bg-[#e30620] px-5 pb-5 pt-4 text-white"><div className="absolute -right-16 -top-20 h-48 w-72 rotate-[22deg] rounded-[42%] bg-[#be071c]/50" /><div className="absolute -left-20 top-20 h-20 w-72 rotate-[22deg] rounded-[50%] bg-[#f13a49]/35" /><div className="relative"><div className="mb-4 flex items-center justify-between text-[12px] font-semibold"><span>09:41</span><span>▮▮▮　5G　<span className="rounded border border-white/70 px-1">82</span></span></div><div className="flex items-center gap-3"><button aria-label="Profil" className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#72767b] active:scale-95"><PanelLeft size={20} /></button><div className="flex h-11 flex-1 items-center gap-2 rounded-full border border-white/70 bg-[#c70a20]/30 px-4"><Search size={19} /><span className="text-[14px]">Zirat Mobil&apos;de Ara</span></div><button aria-label="Mesajlar" className="grid h-11 w-11 place-items-center rounded-xl border border-white/40 bg-white/15 active:scale-95"><MessageSquare size={21} /></button></div><div className="mt-5 text-[15px]">İyi Akşamlar <strong>Muhammed Yılmaz</strong></div></div></header>
      <button className="flex w-full items-center justify-between bg-[#f0eeee] px-5 py-4 text-left text-[17px] font-bold">İpuçlarına hemen göz at! <ChevronDown size={20} className="text-[#db1028]" /></button>
      <div className="px-5 pb-28"><div className="mt-5 flex items-end gap-7 border-b border-[#dedada]"><button onClick={() => setTab("accounts")} className={`relative pb-3 text-[18px] font-semibold ${tab === "accounts" ? "after:absolute after:bottom-[-1px] after:left-0 after:h-[3px] after:w-full after:bg-[#e30620]" : "text-[#87878c]"}`}>Hesaplarım</button><button onClick={() => setTab("cards")} className={`relative pb-3 text-[18px] font-semibold ${tab === "cards" ? "after:absolute after:bottom-[-1px] after:left-0 after:h-[3px] after:w-full after:bg-[#e30620]" : "text-[#87878c]"}`}>Kredi Kartlarım</button><button aria-label="Daha fazla" className="ml-auto mb-2 grid h-10 w-10 place-items-center rounded-xl bg-[#efeeee]"><MoreVertical size={19} /></button></div>
      {tab === "accounts" ? <section className="pt-5"><div className="flex items-center justify-between"><h2 className="text-[17px] font-bold uppercase tracking-wide text-[#c9162d]">Zirat Süper Şube</h2><button aria-label="Hesap seçenekleri" className="grid h-10 w-10 place-items-center rounded-xl bg-[#efeeee]"><MoreVertical size={19} /></button></div><div className="mt-3 flex items-center gap-3"><span className="rounded-lg bg-[#b7a66d] px-3 py-1.5 text-[12px] font-bold text-white">Vadesiz TL</span><span className="text-[14px] text-[#49494d]">4000-104120627-5001</span></div><div className="mt-4 flex items-center justify-between text-[14px] text-[#49494d]"><span>TR31 0001 0090 1041 2062 7050 01</span><ArrowUpRight size={19} className="text-[#d3132b]" /></div><div className="mt-5"><div className="flex items-center gap-2 text-[12px] text-[#6c6a6c]">Bakiye <button onClick={() => setVisible(!visible)} className="text-[#c9162d]">{visible ? "Gizle" : "Göster"}</button></div><div className="text-[22px] font-bold">{visible ? "12.480,75 TL" : "•••••• TL"}</div></div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={() => setView("products")} className="rounded-full bg-[#e30620] py-3.5 text-[14px] font-semibold text-white active:scale-[.98]">Tüm Hesaplarım</button><button onClick={() => setView("transactions")} className="rounded-full bg-[#e30620] py-3.5 text-[14px] font-semibold text-white active:scale-[.98]">Hesap Hareketleri</button></div></section> : <section className="mt-5 rounded-2xl bg-[#f1eded] p-5"><div className="flex items-center gap-3"><CreditCard className="text-[#d3132b]" /><div><p className="font-bold">Zirat Bonus Kart</p><p className="text-sm text-[#777276]">•••• 2468</p></div></div><p className="mt-5 text-sm text-[#777276]">Kullanılabilir limit</p><p className="text-2xl font-bold">28.750,00 TL</p></section>}
      <section className="mt-7 -mx-5 bg-[#f0eeee] px-5 py-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-[18px] font-bold">Kısayollarım</h2><button onClick={() => setView("actions")} className="flex items-center gap-1 text-[13px]">Tüm Kısayollarım <ArrowRight size={17} className="text-[#e30620]" /></button></div><div className="grid grid-cols-4 gap-2">{shortcuts.map(({ label, icon: Icon, tone }) => <button key={label} onClick={() => label.includes("Transfer") ? setPanel("transfer") : label.includes("QR") ? setPanel("qr") : label.includes("Son") ? setView("transactions") : setView("products")} className="flex min-h-[102px] flex-col items-center justify-center gap-2 rounded-xl bg-white px-1 text-center text-[12px] font-medium shadow-sm active:scale-95"><span className={`grid h-9 w-9 place-items-center rounded-full ${tone}`}><Icon size={20} /></span><span className="whitespace-pre-line leading-tight">{label}</span></button>)}</div></section>
      <section className="mt-6 flex items-center justify-between py-2"><h2 className="text-[18px] font-bold">Yaklaşan Talimatlar</h2><ChevronDown size={20} className="text-[#d3132b]" /></section><div className="mt-1 flex items-center gap-3 rounded-xl border border-[#ece7e7] bg-white p-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#fff0f1] text-[#d3132b]"><ReceiptText size={19} /></div><div className="flex-1"><p className="text-sm font-semibold">Kira ödemesi</p><p className="text-xs text-[#858083]">12 Haziran · 4.500,00 TL</p></div><ChevronRight size={18} className="text-[#b2abad]" /></div></div></>}
    {view === "transactions" && <Transactions onBack={() => setView("home")} />}
    {view !== "home" && view !== "transactions" && <UtilityView view={view} onBack={() => setView("home")} onTransfer={() => setPanel("transfer")} />}
    <BottomNav view={view} onChange={setView} />
    {panel && <ActionSheet panel={panel} recipient={recipient} amount={amount} confirmed={confirmed} setRecipient={setRecipient} setAmount={setAmount} onConfirm={() => setConfirmed(true)} onClose={close} />}
  </div></main>;
}

function Transactions({ onBack }: { onBack: () => void }) { return <div className="min-h-[calc(100dvh-76px)] bg-[#fafafa]"><div className="bg-[#e30620] px-4 pb-4 pt-5 text-white"><div className="flex items-center justify-between"><button aria-label="Geri" onClick={onBack}><ArrowLeft /></button><h1 className="text-[20px] font-bold">Son İşlemler</h1><button aria-label="Ana sayfa" onClick={onBack}><Home /></button></div></div><div className="flex gap-5 overflow-hidden border-b bg-white px-3 pt-4 text-[15px]"><span className="border-b-2 border-[#e30620] pb-3 font-bold">Vadesiz Hesap</span><span className="whitespace-nowrap pb-3 text-[#999598]">Kredi Kartı</span><span className="whitespace-nowrap pb-3 text-[#999598]">Diğer Banka Hesaplarım</span></div><div className="flex min-h-[610px] flex-col items-center justify-center px-10 text-center"><div className="mb-6 grid h-16 w-16 place-items-center rounded-2xl border-2 border-[#6e787b] text-[#566164]"><FileText size={34} /></div><h2 className="text-[16px] font-bold leading-snug">Vadesiz hesaplarınıza ait hareket bulunmamaktadır.</h2><p className="mt-3 text-sm text-[#8b8588]">Hesabınızda gerçekleşen işlemler burada listelenir.</p></div></div>; }

function UtilityView({ view, onBack, onTransfer }: { view: View; onBack: () => void; onTransfer: () => void }) { const titles: Record<string, string> = { products: "Ürünler", actions: "İşlemler", applications: "Başvurular", menu: "Tüm Menü" }; const items = view === "actions" ? [["Para transferi", Send], ["QR ile para çekme", QrCode], ["Fatura ödeme", ReceiptText]] : view === "products" ? [["Yeni hesap aç", Landmark], ["Kartlarım", CreditCard], ["Birikim hedefi", PiggyBank]] : [["Kredi başvurusu", FileText], ["Limit artırımı", ArrowUpRight], ["Güvenlik merkezi", ShieldCheck]]; return <div className="min-h-[calc(100dvh-76px)] bg-[#f8f7f7] px-5 pb-28 pt-6"><div className="flex items-center gap-3"><button aria-label="Geri" onClick={onBack} className="grid h-10 w-10 place-items-center rounded-xl bg-white"><ArrowLeft size={19} /></button><h1 className="text-2xl font-bold">{titles[view]}</h1></div><div className="mt-8 rounded-2xl bg-[#e30620] p-5 text-white"><Sparkles size={22} /><p className="mt-4 text-xl font-bold">Günlük bankacılık, tek dokunuşla.</p><p className="mt-2 text-sm text-white/75">Demo alanı · Gerçek hesap bilgisi istemez.</p></div><div className="mt-5 grid gap-3">{items.map(([label, Icon]) => <button key={label as string} onClick={label === "Para transferi" ? onTransfer : undefined} className="flex items-center gap-4 rounded-2xl bg-white p-4 text-left shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#fff0f1] text-[#d3132b]"><Icon size={21} /></span><span className="flex-1 font-semibold">{label as string}</span><ChevronRight size={18} className="text-[#aaa3a6]" /></button>)}</div></div>; }

function BottomNav({ view, onChange }: { view: View; onChange: (v: View) => void }) { return <nav className="fixed bottom-0 left-1/2 z-20 flex h-[76px] w-full max-w-[430px] -translate-x-1/2 items-start justify-around border-t border-[#eee9e9] bg-white px-1 pt-3 shadow-[0_-3px_14px_rgba(60,35,37,.05)]">{navItems.map(({ label, view: target, icon: Icon }) => <button key={label} onClick={() => onChange(target)} className={`flex w-1/5 flex-col items-center gap-1 text-[11px] font-semibold ${view === target ? "text-[#df0b25]" : "text-[#777477]"}`}><Icon size={20} /><span>{label}</span>{view === target && <span className="h-1.5 w-1.5 rounded-full bg-[#df0b25]" />}</button>)}</nav>; }

function ActionSheet({ panel, recipient, amount, confirmed, setRecipient, setAmount, onConfirm, onClose }: { panel: Panel; recipient: string; amount: string; confirmed: boolean; setRecipient: (v: string) => void; setAmount: (v: string) => void; onConfirm: () => void; onClose: () => void }) { if (!panel) return null; const title = panel === "transfer" ? "Para transferi" : panel === "qr" ? "QR ile para çekme" : "Fatura ödeme"; return <div className="fixed inset-0 z-30 flex items-end justify-center bg-[#2b2021]/40"><div className="w-full max-w-[430px] rounded-t-[28px] bg-[#fffdfd] px-5 pb-8 pt-4"><div className="mx-auto mb-5 h-1.5 w-12 rounded-full bg-[#d8d2d3]" /><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{confirmed ? "İşlem tamamlandı" : title}</h2><button aria-label="Kapat" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full bg-[#f2eeee]"><X size={18} /></button></div>{confirmed ? <div className="py-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#e2f5e9] text-[#16834b]"><Check size={32} /></div><p className="mt-4 text-lg font-bold">Demo işlem başarıyla oluşturuldu</p><p className="mt-2 text-sm text-[#777174]">Gerçek ödeme yapılmadı. İşlem detaylarını güvenle inceleyebilirsin.</p><button onClick={onClose} className="mt-7 w-full rounded-full bg-[#e30620] py-3.5 font-semibold text-white">Ana sayfaya dön</button></div> : panel === "transfer" ? <div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Alıcı adı<input value={recipient} onChange={e => setRecipient(e.target.value)} className="mt-2 w-full rounded-xl border border-[#e2dcdd] bg-[#faf8f8] px-4 py-3 outline-none focus:border-[#e30620]" /></label><label className="block text-sm font-semibold">Tutar<input value={amount} onChange={e => setAmount(e.target.value)} className="mt-2 w-full rounded-xl border border-[#e2dcdd] bg-[#faf8f8] px-4 py-3 outline-none focus:border-[#e30620]" /></label><div className="rounded-xl bg-[#fff3f4] p-3 text-xs text-[#9a4c54]">Demo güvenlik notu: IBAN, şifre veya kart bilgisi istemiyoruz.</div><button onClick={onConfirm} className="w-full rounded-full bg-[#e30620] py-3.5 font-semibold text-white">Transferi onayla</button></div> : <div className="py-8"><div className="mx-auto grid h-24 w-24 place-items-center rounded-2xl border-2 border-dashed border-[#e30620] text-[#e30620]"><QrCode size={54} /></div><p className="mt-5 text-center text-sm text-[#706a6d]">{panel === "qr" ? "ATM ekranındaki QR kodu tarayarak güvenle devam edin." : "Ödemek istediğiniz faturayı seçin."}</p><button onClick={onConfirm} className="mt-6 w-full rounded-full bg-[#e30620] py-3.5 font-semibold text-white">{panel === "qr" ? "Demo QR okut" : "Fatura seç"}</button></div>}</div></div>; }